SUPABASE_URL = "https://jwzcdbubnkxtohpwxrrf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3emNkYnVibmt4dG9ocHd4cnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTU4ODIsImV4cCI6MjA1ODU3MTg4Mn0.-qXh6VQtPJeAT9d5WXLyraOC2wFKHMP4lRyvwncwi4I"
